AllCops:
  Exclude:
    - "db/migrate/*"
    - "db/schema.rb"
    - "db/legacy_schema.rb"
    - "db/seeds.rb"
    - "script/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "Gemfile"
    - "unused/*"
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  Safe: true
Layout/LineLength:
  AutoCorrect: true
  Max: 100
  Exclude:
    - "config/initializers/devise.rb"
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/FrozenStringLiteralComment:
  Enabled: true
  Safe: true
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/**/*"
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "config/routes.rb"
    - "lib/tasks/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/AbcSize:
  Max: 30
